# Generated by Django 5.1.4 on 2025-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_auto_20240226_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
