# Generated by Django 5.1.4 on 2025-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_options_alter_cartitem_quantity"),
        ("products", "0003_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["-created_at"], name="cart_cartit_created_10634c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_cartit_cart_id_4fb076_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="cart_cartit_product_985dba_idx"
            ),
        ),
    ]
