# Generated by Django 5.1.4 on 2025-01-11 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastereport",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                help_text="Image must clearly show the waste type",
                upload_to="waste_images/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wastereport",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("cardboard", "Cardboard"),
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("paper", "Paper"),
                    ("plastic", "Plastic"),
                    ("trash", "Trash"),
                ],
                help_text="Type of waste material",
                max_length=10,
            ),
        ),
    ]
