# Generated by Django 5.1.4 on 2025-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="carbon_saved",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="CO2 emissions saved in kg",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_waste_collected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="total_waste_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="trees_saved",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Equivalent number of trees saved",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="water_saved",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Water saved in liters",
                max_digits=10,
            ),
        ),
    ]
